apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
rules:
- apiGroups:
  - employee.appscode.com
  - other.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources:
    - serviceaccounts
  verbs: ["create", "get", "patch", "list", "watch"]
- apiGroups:
    - ""
  resources:
    - events
  verbs: ["*"]